// GENERATED by scripts/gen-counts.mjs. Do not edit by hand.
//
// Counted from the specs `npm test` runs: edges.ts 13, read-receipt.ts 5, sinbazaar.ts 19.
// `vrf-stall.ts` is excluded because the default suite excludes it.
export const TEST_COUNT = 37;
