#!/usr/bin/env node
/**
 * Generate the test count the landing page prints.
 *
 * It used to be a hand-written `const TEST_COUNT = 32`, and it drifted: the
 * suite grew to 37 and the page went on claiming 32. A wrong number on the
 * landing page is worse than no number, because the whole pitch rests on
 * nothing here being exaggerated.
 *
 * Counts `it(` across the files `npm test` actually runs. `vrf-stall.ts` is
 * excluded because it is excluded from the default suite (it needs a stopped
 * oracle), and `harness.ts` holds no specs. Verified against mocha: 13 + 5 + 19
 * = 37, which is exactly what the runner reports.
 *
 *   node scripts/gen-counts.mjs           write app/src/lib/counts.ts
 *   node scripts/gen-counts.mjs --check   fail if the file is out of date
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const testsDir = join(root, "tests");
const out = join(root, "app", "src", "lib", "counts.ts");
const SKIP = new Set(["vrf-stall.ts", "harness.ts"]);

const files = readdirSync(testsDir).filter((f) => f.endsWith(".ts") && !SKIP.has(f)).sort();
let total = 0;
const per = [];
for (const f of files) {
  const n = (readFileSync(join(testsDir, f), "utf8").match(/^\s*it\(/gm) || []).length;
  per.push(`${f} ${n}`);
  total += n;
}

const body = `// GENERATED by scripts/gen-counts.mjs. Do not edit by hand.
//
// Counted from the specs \`npm test\` runs: ${per.join(", ")}.
// \`vrf-stall.ts\` is excluded because the default suite excludes it.
export const TEST_COUNT = ${total};
`;

if (process.argv.includes("--check")) {
  let current = "";
  try { current = readFileSync(out, "utf8"); } catch { /* missing counts as drift */ }
  if (current !== body) {
    console.error(`counts out of date: tests hold ${total} specs; run npm run gen:counts`);
    process.exit(1);
  }
  console.log(`counts in sync: ${total} tests`);
} else {
  writeFileSync(out, body);
  console.log(`wrote TEST_COUNT = ${total}`);
}
